// Demo colleagues for the Northgate floor. Replaced by real people from the API in Phase 02.
import type { Person } from '@knovra/shared';

export const people: Person[] = [
  {
    id: 'asha',
    name: 'Asha Rao',
    role: 'Eng manager',
    team: 'platform',
    where: 'remote',
    status: 'meeting',
    body: '#4f7cac',
    skin: '#c68b62',
    hair: '#2b1d16',
    desk: 'platform-0',
  },
  {
    id: 'tomas',
    name: 'Tomás Ortega',
    role: 'Backend',
    team: 'platform',
    where: 'office',
    status: 'available',
    body: '#e07a5f',
    skin: '#e2b48f',
    hair: '#4a3222',
    desk: 'platform-1',
  },
  {
    id: 'mei',
    name: 'Mei Lin',
    role: 'SRE',
    team: 'platform',
    where: 'remote',
    status: 'focus',
    body: '#3d8a7a',
    skin: '#efc9a4',
    hair: '#151515',
    desk: 'platform-2',
  },
  {
    id: 'kofi',
    name: 'Kofi Mensah',
    role: 'Backend',
    team: 'platform',
    where: 'remote',
    status: 'meeting',
    body: '#8d6cab',
    skin: '#7a4b2f',
    hair: '#120c08',
    desk: 'platform-3',
  },
  {
    id: 'lena',
    name: 'Lena Fischer',
    role: 'Product designer',
    team: 'design',
    where: 'office',
    status: 'available',
    body: '#d9a441',
    skin: '#f1cfb1',
    hair: '#b07a3c',
    desk: 'design-0',
  },
  {
    id: 'arjun',
    name: 'Arjun Nair',
    role: 'UX research',
    team: 'design',
    where: 'remote',
    status: 'available',
    body: '#5b8f4e',
    skin: '#a8704a',
    hair: '#1b1411',
    desk: 'design-1',
  },
  {
    id: 'sofia',
    name: 'Sofia Costa',
    role: 'Brand',
    team: 'design',
    where: 'remote',
    status: 'away',
    body: '#c45d7a',
    skin: '#d9a27c',
    hair: '#5a2e1c',
    desk: 'design-2',
  },
  {
    id: 'noah',
    name: 'Noah Kim',
    role: 'Support lead',
    team: 'support',
    where: 'office',
    status: 'available',
    body: '#4a6fa5',
    skin: '#ecc19c',
    hair: '#202020',
    desk: 'support-0',
  },
  {
    id: 'priya',
    name: 'Priya Shah',
    role: 'Support',
    team: 'support',
    where: 'remote',
    status: 'available',
    body: '#b5654d',
    skin: '#b67c56',
    hair: '#1a110c',
    desk: 'support-1',
  },
  {
    id: 'ola',
    name: 'Ola Nowak',
    role: 'Support',
    team: 'support',
    where: 'remote',
    status: 'focus',
    body: '#6b8f9c',
    skin: '#f3d3b8',
    hair: '#c9a46b',
    desk: 'support-2',
  },
  {
    id: 'sam',
    name: 'Sam Okafor',
    role: 'Solutions',
    team: 'support',
    where: 'office',
    status: 'available',
    body: '#9a7b4f',
    skin: '#6e4329',
    hair: '#0e0a07',
    desk: 'support-3',
  },
];

export const ME = { name: 'You', body: '#2f6f8f', skin: '#d6a07a', hair: '#3a2416' };
